import Head from "next/head";
import Link from "next/link";
import blogs from "../data/blogs.js";

const Home = () => {
  // console.log(blogs);
  return (
    <div className={`container`}>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="my-5">
        <div className="d-flex justify-content-center">
          <div className="row">
            {blogs.map((blog, index) => {
              return (
                <div key={index} className="col-md-3 col-sm-6 col-12 my-2">
                  <div className="p-3 shadow rounded">
                    <Link href={`blog/${blog.slug}`} className="text-decoration-none">
                      <h2>{blog.title}</h2>
                    </Link>
                    <p className="">{`${blog.desc.substring(0, 60)}...`}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
}


export default Home;